"""initial migration

Revision ID: 58172627e1ca
Revises: 
Create Date: 2025-02-27 18:25:49.023339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58172627e1ca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prix_results',
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('prix_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('placement', sa.Integer(), nullable=False),
    sa.Column('starting_elo', sa.Integer(), nullable=False),
    sa.Column('elo_adjustment', sa.Integer(), nullable=False),
    sa.Column('ending_elo', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['prix_id'], ['prixs.prix_id'], ),
    sa.PrimaryKeyConstraint('result_id'),
    sa.UniqueConstraint('prix_id', 'player_id', name='uq_prix_player')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prix_results')
    # ### end Alembic commands ###
